### ISSUE TITLE
How to update generated code

### ISSUE THREAD

**Issue by grant-d** [samholt/L2MAC#5] opened 2024-06-21 23:05 UTC
Wonderful paper and implementation. Thank you.

Do you have guidance as to how you'd update (eg) the snake code, vs generate it from scratch?
For example, how would you change the code so that this would work:
`L2MAC --foo "update the grid to be 50 x 50"`

**Comment by samholt** [comment] 2024-07-02 23:21
Thank you!

Yes, that is quite easy, and the original implementation before relating it publically supported this. This is on the feature roadmap to implement this in a good way, so I welcome any contributions to do this.

It's somewhat straightforward. All you need is a function to load an existing codebase / repository of folders and files, into a nested dictionary, change the prompts to then have knowledge of this codebase, and use the existing codebase, and it should work. This was done in the original implementation in the paper, and you can see examples of this working in the appendix.

Thank you. If you want I can also try to provide an implementation in the next 2-4 months.

Best,
Sam

**Comment by samholt** [comment] 2024-12-27 00:18
Hi @grant-d,

Thank you for your interest; if this is still a feature you would like implemented, please let me know, otherwise closing this as a bug for now, as L2MAC works as intended,

Best,
Sam

**Closed by samholt** 2024-12-27 00:18 UTC

**Comment by grant-d** [comment] 2024-12-27 01:32
np, thanks

**Comment by toshan121** [comment] 2024-12-31 11:12
+1 for this feature.
